---

stages:
  - lint
  - test
  - autorel
  - build
  - release

#
# Check that the commit message is in conventional-commit
# format (https://www.conventionalcommits.org/).
# As a special case if this is a merge request, allow that
# format.
lint:
  stage: lint
  image: cr.agilicus.com/corp-tools/build-containers/conform
  script: |
    [ -n "$CI_MERGE_REQUEST_ID" ] && /usr/local/bin/conform enforce || true

#
# Run any tests against the code that we want prior to doing a release
test:
  stage: test
  image: cr.agilicus.com/applications/php
  services:
    - name: cockroachdb/cockroach:v19.2.6
      alias: cockroachdb
      command: ['start-single-node', '--insecure', '--store=type=mem,size=640MiB', '--max-offset=5ms', '--log-file-verbosity=WARNING', '--logtostderr=ERROR']
    - name: cr.agilicus.com/open-source/titan:integration
  variables:
    DB_PORT_3306_TCP_ADDR: "127.0.0.1"
    DB_PORT_3306_TCP_PORT: "26257"
    DB_ENV_PGSQL_DATABASE: defaultdb
    DB_ENV_PGSQL_USER: root
    DB_ENV_PGSQL_PASSWORD: hello
    REDIS_HOST: "127.0.0.1"
    REDIS_PORT: "7369"
    DEBUG: "true"
  script: |
    ln -sf $PWD /var/www/moodle

    mkdir -p /var/www/phpunitdata /var/moodledata
    cp docker/moodle-config.php config.php
    php docker/install_plugins.php

    doit() {
      echo "------------------------------------------"
      echo "Execute $*"
      time "$@"
      echo ""
      echo "------------------------------------------"
    }

    doit php admin/tool/phpunit/cli/init.php --parallel=4

    # limited selection of core tests
    doit vendor/bin/phpunit lib/ddl/tests/ddl_test.php
    doit vendor/bin/phpunit "core_dml_testcase" lib/dml/tests/dml_test.php
    doit vendor/bin/phpunit lib/tests/lock_test.php
    doit vendor/bin/phpunit user/tests/editlib_test.php

    # limited selection of the non-broken iomad tests
    doit vendor/bin/phpunit local/iomad/tests/filter_iomad_filter_test.php
    doit vendor/bin/phpunit local/iomad/tests/filter_manager_test.php
    doit vendor/bin/phpunit local/iomad/tests/navigationlib_test.php
    vendor/bin/phpunit local/iomad/tests/weblib_format_text_test.php
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

#
# Run `conventional-changelog -p angular -i CHANGELOG.md -s -r 0`
# the first time to generate the initial CHANGELOG.md from empty
#
# (only on the master branch) created a 'standard release'
# [see](https://github.com/conventional-changelog/standard-version)
# - update CHANGELOG.md
# - create a tag vM.m.b
# - push tag to repo
# - push CHANGELOG.md to repo
# The use of 'conventional-commit' messages is required (fix/feat)
# see [conventional-commits](https://www.conventionalcommits.org/)
#
autorel:
  stage: autorel
  image: cr.agilicus.com/corp-tools/build-containers/release
  script: |
    set -x
    if [ -n "$CI_COMMIT_TAG" ]
    then
      echo "Skip autorel, CI_COMMIT_TAG=$CI_COMMIT_TAG is present"
    else
      node-release
    fi
  only:
    - integration
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

#
# This stage does a docker build, and then push to registry
# The image will be called 'group/repo:branch'
# If branch == master, it will also be pushed to 'latest'
# If a commit tag vM.m.b exists, then the image will also be tagged as
#  - image:M.m.b
#  - image:M.m
#  - image:M
#
build:
  stage: build
  image: cr.agilicus.com/corp-tools/docker-compose
  services:
    - name: docker:dind
  script: |
    std-build-tag-push Dockerfile -b integration

#
# If a tag is present, this could mean that the 'autorel' has
# fired, and that a build of that is now present, we might
# choose to push to external repo etc.
#
release:
  stage: release
  image: cr.agilicus.com/corp-tools/build-containers/release
  script: |
    echo "A new release, tag is $CI_COMMIT_TAG"
    # nothing to do here
  except:
    - branches
  only:
    - tags
